# k8s secrets for the application
kind: Secret
apiVersion: v1
metadata:
    name: postgres-secret
    namespace: constant-tracker
type: Opaque
data:
    POSTGRES_USER: <your-base64-encoded-username>
    POSTGRES_PASSWORD: <your-base64-encoded-password>

---
kind: Secret
apiVersion: v1
metadata:
    name: app-secret
    namespace: constant-tracker
type: Opaque
data:
  SPRING_R2DBC_USERNAME: <your-base64-encoded-username>
  SPRING_R2DBC_PASSWORD: <your-base64-encoded-password>
  SPRING_FLYWAY_USER: <your-base64-encoded-username>
  SPRING_FLYWAY_PASSWORD: <your-base64-encoded-password>